# Generated by Django 4.0.3 on 2022-03-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_alter_set_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='category',
            field=models.CharField(choices=[('warmup', 'Warm-Up'), ('mainset', 'Main Set'), ('cooldown', 'Cool-Down')], default='mainset', max_length=20),
        ),
    ]
